source 'https://rubygems.org'
ruby '2.3.3'

gem 'rails', '5.0.3'
gem 'puma'
gem 'pg'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'redis'
gem 'sprockets-rails'
gem 'sass-rails'
gem 'jquery-rails'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form'
gem 'autoprefixer-rails'
gem 'cloudinary'
# gem 'kaminari'
gem 'searchkick'
gem 'will_paginate'
gem 'carrierwave', '~> 0.11.2'
gem 'sidekiq'

gem 'mechanize'
gem 'capybara'
gem 'poltergeist'
gem 'oj'
gem 'typhoeus'
gem 'jquery-ui-rails'

group :development, :test do
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'listen', '~> 3.0.5'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


